name = "unbelong-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 データベースバインディング
[[d1_databases]]
binding = "DB"
database_name = "unbelong-db"
database_id = "60316b26-074e-4fd3-a06b-272bc198b6b1"

# 環境変数
[env.production]
name = "unbelong-api"

[env.staging]
name = "unbelong-api-staging"

# CORS設定
[env.production.vars]
ALLOWED_ORIGINS = "https://admin.unbelong.xyz,https://comic.unbelong.xyz,https://illust.unbelong.xyz"

[env.staging.vars]
ALLOWED_ORIGINS = "*"
